config/routes.rb
#Листинг 3.5: Маршруты для действий home и help в контроллере StaticPages. config/routes.rb 

#Листинг 3.37: Установка корневого маршрута на страницу Home. config/routes.rb
#Листинг 5.22: Маршруты для статических страниц. config/routes.rb  Листинг 8.1: Добавление ресурса для получения стандартных RESTful действий для сессий. config/routes.rb Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb 
Rails.application.routes.draw do
 root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]

end

app/views/layouts/_footer.html.erb
<!-- #Листинг 5.11: Партиал для подвала сайта. app/views/layouts/_footer.html.erb
Листинг 5.24: Партиал подвала со ссылками. app/views/layouts/_footer.html.erb -->
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%#= link_to "About",   about_path %></li>
      <li><%#= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--#Листинг 5.10: Партиал для заголовка сайта. app/views/layouts/_header.html.erb
#Листинг 5.23: Партиал заголовка со ссылками. app/views/layouts/_header.html.erb Листинг 8.16: Изменение ссылок шаблона для вошедших пользователей. app/views/layouts/_header.html.erb Листинг 9.36: Добавление URL к ссылке на список пользователей. app/views/layouts/_header.html.erb --> 
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "June_13 ruby 2.6.3 _march02", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
                    <li><%= link_to "Users", users_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
   <ul class="dropdown-menu">
      <li><%= link_to "Profile", current_user %></li>
  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--#Листинг 5.9: Партиал для HTML shim. app/views/layouts/_shim.html.erb
-->
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!--#Листинг 3.32: Макет сайта учебного приложения. ЗЕЛЕНЫЙ app/views/layouts/application.html.erb
#Листинг 4.1: Макет сайта учебного приложения. app/views/layouts/application.html.erb
#Листинг 4.3: Шаблон сайта с хелпером full_title. ЗЕЛЕНЫЙ app/views/layouts/application.html.erb

#Листинг 5.1: Шаблон сайта с добавленными структурами. app/views/layouts/application.html.erb
#Листинг 5.8: Макет сайта с партиалами для таблицы стилей и заголовка. app/views/layouts/application.html.erb Листинг 7.25: Добавление содержимого переменной flash к шаблону сайта. app/views/layouts/application.html.erb 
#Листинг 7.1: Добавление отладочной информации к шаблону сайта. app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
 <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>